/* Generated By:JavaCC: Do not edit this line. ISDLParserConstants.java */
package avrora.core.isdl;

public interface ISDLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int INTEGER_LITERAL = 13;
  int DECIMAL_LITERAL = 14;
  int HEX_LITERAL = 15;
  int BIN_LITERAL = 16;
  int OCTAL_LITERAL = 17;
  int CHARACTER_LITERAL = 18;
  int STRING_LITERAL = 19;
  int INSTRUCTION = 20;
  int ARCHITECTURE = 21;
  int FORMAT = 22;
  int OPERAND = 23;
  int WHERE = 24;
  int REGISTER = 25;
  int IMMEDIATE = 26;
  int ADDRESS = 27;
  int ENCODING = 28;
  int EXECUTE = 29;
  int LOCAL = 30;
  int IF = 31;
  int ELSE = 32;
  int AND = 33;
  int OR = 34;
  int XOR = 35;
  int LBRACKET = 36;
  int RBRACKET = 37;
  int EQUALS = 38;
  int COMMA = 39;
  int LPAREN = 40;
  int RPAREN = 41;
  int SEMI = 42;
  int SHIFTLEFT = 43;
  int SHIFTRIGHT = 44;
  int ADD = 45;
  int SUB = 46;
  int MUL = 47;
  int DIV = 48;
  int B_AND = 49;
  int B_OR = 50;
  int B_XOR = 51;
  int NOT = 52;
  int B_COMP = 53;
  int EQUAL = 54;
  int NOTEQUAL = 55;
  int LESS = 56;
  int LESSEQ = 57;
  int GREATER = 58;
  int GREATEREQ = 59;
  int DOLLAR = 60;
  int IDENTIFIER = 61;
  int LETTER = 62;
  int DIGIT = 63;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<BIN_LITERAL>",
    "<OCTAL_LITERAL>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"instruction\"",
    "\"architecture\"",
    "\"format\"",
    "\"operand\"",
    "\"where\"",
    "\"register\"",
    "\"immediate\"",
    "\"address\"",
    "\"encoding\"",
    "\"execute\"",
    "\"local\"",
    "\"if\"",
    "\"else\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"!\"",
    "\"~\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"$\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\":\"",
    "\"[\"",
    "\"]\"",
  };

}
