/* Generated By:JavaCC: Do not edit this line. GASParserConstants.java */
package avrora.syntax.gas;

public interface GASParserConstants {

    int EOF = 0;
    int SINGLE_LINE_COMMENT = 9;
    int FORMAL_COMMENT = 10;
    int MULTI_LINE_COMMENT = 11;
    int INTEGER_LITERAL = 13;
    int DECIMAL_LITERAL = 14;
    int HEX_LITERAL = 15;
    int BIN_LITERAL = 16;
    int OCTAL_LITERAL = 17;
    int CHARACTER_LITERAL = 18;
    int STRING_LITERAL = 19;
    int LO8 = 20;
    int HI8 = 21;
    int BYTE = 22;
    int WORD = 23;
    int LONG = 24;
    int FILE = 25;
    int INCLUDE = 26;
    int TYPE = 27;
    int ARCH = 28;
    int EQU = 29;
    int ORG = 30;
    int DATA = 31;
    int LIST = 32;
    int NOLIST = 33;
    int SKIPS = 34;
    int TEXT = 35;
    int SPACE = 36;
    int GLOBAL = 37;
    int SIZE = 38;
    int ADD = 39;
    int ADC = 40;
    int ADIW = 41;
    int AND = 42;
    int ANDI = 43;
    int ASR = 44;
    int BCLR = 45;
    int BLD = 46;
    int BRBC = 47;
    int BRBS = 48;
    int BRCC = 49;
    int BRCS = 50;
    int BREAK = 51;
    int BREQ = 52;
    int BRGE = 53;
    int BRHC = 54;
    int BRHS = 55;
    int BRID = 56;
    int BRIE = 57;
    int BRLO = 58;
    int BRLT = 59;
    int BRMI = 60;
    int BRNE = 61;
    int BRPL = 62;
    int BRSH = 63;
    int BRTC = 64;
    int BRTS = 65;
    int BRVC = 66;
    int BRVS = 67;
    int BSET = 68;
    int BST = 69;
    int CALL = 70;
    int CBI = 71;
    int CBR = 72;
    int CLC = 73;
    int CLH = 74;
    int CLI = 75;
    int CLN = 76;
    int CLR = 77;
    int CLS = 78;
    int CLT = 79;
    int CLV = 80;
    int CLZ = 81;
    int COM = 82;
    int CP = 83;
    int CPC = 84;
    int CPI = 85;
    int CPSE = 86;
    int DEC = 87;
    int EICALL = 88;
    int EIJMP = 89;
    int ELPM = 90;
    int EOR = 91;
    int FMUL = 92;
    int FMULS = 93;
    int FMULSU = 94;
    int ICALL = 95;
    int IJMP = 96;
    int IN = 97;
    int INC = 98;
    int JMP = 99;
    int LD = 100;
    int LDD = 101;
    int LDI = 102;
    int LDS = 103;
    int LPM = 104;
    int LSL = 105;
    int LSR = 106;
    int MOV = 107;
    int MOVW = 108;
    int MUL = 109;
    int MULS = 110;
    int MULSU = 111;
    int NEG = 112;
    int NOP = 113;
    int OR = 114;
    int ORI = 115;
    int OUT = 116;
    int POP = 117;
    int PUSH = 118;
    int RCALL = 119;
    int RET = 120;
    int RETI = 121;
    int RJMP = 122;
    int ROL = 123;
    int ROR = 124;
    int SBC = 125;
    int SBCI = 126;
    int SBI = 127;
    int SBIC = 128;
    int SBIS = 129;
    int SBIW = 130;
    int SBR = 131;
    int SBRC = 132;
    int SBRS = 133;
    int SEC = 134;
    int SEH = 135;
    int SEI = 136;
    int SEN = 137;
    int SER = 138;
    int SES = 139;
    int SET = 140;
    int SEV = 141;
    int SEZ = 142;
    int SLEEP = 143;
    int SPM = 144;
    int ST = 145;
    int STD = 146;
    int STS = 147;
    int SUB = 148;
    int SUBI = 149;
    int SWAP = 150;
    int TST = 151;
    int WDR = 152;
    int IDENTIFIER = 153;
    int LETTER = 154;
    int DIGIT = 155;

    int DEFAULT = 0;
    int IN_SINGLE_LINE_COMMENT = 1;
    int IN_FORMAL_COMMENT = 2;
    int IN_MULTI_LINE_COMMENT = 3;

    String[] tokenImage = {
        "<EOF>",
        "\" \"",
        "\"\\t\"",
        "\"\\n\"",
        "\"\\r\"",
        "\"\\f\"",
        "\";\"",
        "<token of kind 7>",
        "\"/*\"",
        "<SINGLE_LINE_COMMENT>",
        "\"*/\"",
        "\"*/\"",
        "<token of kind 12>",
        "<INTEGER_LITERAL>",
        "<DECIMAL_LITERAL>",
        "<HEX_LITERAL>",
        "<BIN_LITERAL>",
        "<OCTAL_LITERAL>",
        "<CHARACTER_LITERAL>",
        "<STRING_LITERAL>",
        "\"lo8\"",
        "\"hi8\"",
        "\".byte\"",
        "\".word\"",
        "\".long\"",
        "\".file\"",
        "\".include\"",
        "\".type\"",
        "\".arch\"",
        "\".equ\"",
        "\".org\"",
        "\".data\"",
        "\".list\"",
        "\".nolist\"",
        "\".skip\"",
        "\".text\"",
        "\".space\"",
        "\".global\"",
        "\".size\"",
        "\"add\"",
        "\"adc\"",
        "\"adiw\"",
        "\"and\"",
        "\"andi\"",
        "\"asr\"",
        "\"bclr\"",
        "\"bld\"",
        "\"brbc\"",
        "\"brbs\"",
        "\"brcc\"",
        "\"brcs\"",
        "\"break\"",
        "\"breq\"",
        "\"brge\"",
        "\"brhc\"",
        "\"brhs\"",
        "\"brid\"",
        "\"brie\"",
        "\"brlo\"",
        "\"brlt\"",
        "\"brmi\"",
        "\"brne\"",
        "\"brpl\"",
        "\"brsh\"",
        "\"brtc\"",
        "\"brts\"",
        "\"brvc\"",
        "\"brvs\"",
        "\"bset\"",
        "\"bst\"",
        "\"call\"",
        "\"cbi\"",
        "\"cbr\"",
        "\"clc\"",
        "\"clh\"",
        "\"cli\"",
        "\"cln\"",
        "\"clr\"",
        "\"cls\"",
        "\"clt\"",
        "\"clv\"",
        "\"clz\"",
        "\"com\"",
        "\"cp\"",
        "\"cpc\"",
        "\"cpi\"",
        "\"cpse\"",
        "\"dec\"",
        "\"eicall\"",
        "\"eijmp\"",
        "\"elpm\"",
        "\"eor\"",
        "\"fmul\"",
        "\"fmuls\"",
        "\"fmulsu\"",
        "\"icall\"",
        "\"ijmp\"",
        "\"in\"",
        "\"inc\"",
        "\"jmp\"",
        "\"ld\"",
        "\"ldd\"",
        "\"ldi\"",
        "\"lds\"",
        "\"lpm\"",
        "\"lsl\"",
        "\"lsr\"",
        "\"mov\"",
        "\"movw\"",
        "\"mul\"",
        "\"muls\"",
        "\"mulsu\"",
        "\"neg\"",
        "\"nop\"",
        "\"or\"",
        "\"ori\"",
        "\"out\"",
        "\"pop\"",
        "\"push\"",
        "\"rcall\"",
        "\"ret\"",
        "\"reti\"",
        "\"rjmp\"",
        "\"rol\"",
        "\"ror\"",
        "\"sbc\"",
        "\"sbci\"",
        "\"sbi\"",
        "\"sbic\"",
        "\"sbis\"",
        "\"sbiw\"",
        "\"sbr\"",
        "\"sbrc\"",
        "\"sbrs\"",
        "\"sec\"",
        "\"seh\"",
        "\"sei\"",
        "\"sen\"",
        "\"ser\"",
        "\"ses\"",
        "\"set\"",
        "\"sev\"",
        "\"sez\"",
        "\"sleep\"",
        "\"spm\"",
        "\"st\"",
        "\"std\"",
        "\"sts\"",
        "\"sub\"",
        "\"subi\"",
        "\"swap\"",
        "\"tst\"",
        "\"wdr\"",
        "<IDENTIFIER>",
        "<LETTER>",
        "<DIGIT>",
        "\",\"",
        "\"+\"",
        "\"-\"",
        "\":\"",
        "\"=\"",
        "\"@\"",
        "\"||\"",
        "\"&&\"",
        "\"|\"",
        "\"^\"",
        "\"&\"",
        "\"==\"",
        "\"!=\"",
        "\">\"",
        "\">=\"",
        "\"<\"",
        "\"<=\"",
        "\"<<\"",
        "\">>\"",
        "\"*\"",
        "\"/\"",
        "\"!\"",
        "\"~\"",
        "\"(\"",
        "\")\"",
    };

}
