/* Generated By:JavaCC: Do not edit this line. ISDLParserConstants.java */
package jintgen.isdl.parser;

public interface ISDLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 9;
  int FORMAL_COMMENT = 10;
  int MULTI_LINE_COMMENT = 11;
  int INTEGER_LITERAL = 13;
  int DECIMAL_LITERAL = 14;
  int HEX_LITERAL = 15;
  int BIN_LITERAL = 16;
  int OCTAL_LITERAL = 17;
  int CHARACTER_LITERAL = 18;
  int STRING_LITERAL = 19;
  int INSTRUCTION = 20;
  int ARCHITECTURE = 21;
  int FORMAT = 22;
  int OPERAND = 23;
  int OPERAND_TYPE = 24;
  int ADDR_MODE = 25;
  int ADDR_SET = 26;
  int READ = 27;
  int WRITE = 28;
  int WHERE = 29;
  int PRIORITY = 30;
  int ENCODING = 31;
  int EXECUTE = 32;
  int LOCAL = 33;
  int GLOBAL = 34;
  int MEMORY = 35;
  int MAPPING = 36;
  int IF = 37;
  int ELSE = 38;
  int AND = 39;
  int OR = 40;
  int XOR = 41;
  int SUBROUTINE = 42;
  int INLINE = 43;
  int EXTERNAL = 44;
  int RETURN = 45;
  int BOOLEAN_LITERAL = 46;
  int SYMBOL = 47;
  int PSEUDO = 48;
  int WHEN = 49;
  int PROPERTY = 50;
  int LBRACKET = 51;
  int RBRACKET = 52;
  int EQUALS = 53;
  int COMMA = 54;
  int LPAREN = 55;
  int RPAREN = 56;
  int SEMI = 57;
  int SHIFTLEFT = 58;
  int SHIFTRIGHT = 59;
  int ADD = 60;
  int SUB = 61;
  int MUL = 62;
  int DIV = 63;
  int B_AND = 64;
  int B_OR = 65;
  int B_XOR = 66;
  int NOT = 67;
  int B_COMP = 68;
  int EQUAL = 69;
  int NOTEQUAL = 70;
  int LESS = 71;
  int LESSEQ = 72;
  int GREATER = 73;
  int GREATEREQ = 74;
  int DOLLAR = 75;
  int IDENTIFIER = 76;
  int LETTER = 77;
  int DIGIT = 78;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_FORMAL_COMMENT = 2;
  int IN_MULTI_LINE_COMMENT = 3;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 12>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<BIN_LITERAL>",
    "<OCTAL_LITERAL>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"instruction\"",
    "\"architecture\"",
    "\"format\"",
    "\"operand\"",
    "\"operand-type\"",
    "\"addr-mode\"",
    "\"addr-set\"",
    "\"read\"",
    "\"write\"",
    "\"where\"",
    "\"priority\"",
    "\"encoding\"",
    "\"execute\"",
    "\"local\"",
    "\"global\"",
    "\"memory\"",
    "\"mapping\"",
    "\"if\"",
    "\"else\"",
    "\"and\"",
    "\"or\"",
    "\"xor\"",
    "\"subroutine\"",
    "\"inline\"",
    "\"external\"",
    "\"return\"",
    "<BOOLEAN_LITERAL>",
    "\"symbol\"",
    "\"pseudo\"",
    "\"when\"",
    "\"property\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"!\"",
    "\"~\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"$\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\"sub-operand\"",
    "\".\"",
  };

}
